### ISSUE TITLE
Remove the plugin's UI after it's disabled or removed from the directory.

### ISSUE THREAD

**Issue by Lunari8546** [pickaxe828/Discord-Stories#1]
Even you disabled or removed the plugin, the UI (Bubble box) still remains until restarting Discord. Injecting the CSS in start() and removing the CSS in stop() instead of putting it in UIinit() would fix the issue. [Example]( https://github.com/Mega-Mewthree/BetterDiscordPlugins/blob/master/Plugins/DiscordCakeDay/DiscordCakeDay.plugin.js)

**Comment by pickaxe828** [comment]
That problem could be fixed by reopening the friend tab. But that will be fixed later on (polishing updates?) with implementing delete the parent element on `start()`
